image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r api-server/* .public
  - cp -r webapp/* .public
  - mv .public public
  - cd public
  - gem install bundle  --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor # Install dependencies into ./vendor/ruby
  artifacts:
    paths:
    - public
  only:
  - master
